### ISSUE TITLE
Sqlite Database is Locked is Coming, and Marmot is Crashing After Continusouly Inserting For Long time. 

### ISSUE THREAD

**Issue by tania-anand** [maxpert/marmot#36]
Hi, I am trying to set up an SQLite cluster using marmot, while writing to node1 with the rate of 500 records in 5 seconds, continuously 
I am getting a database-locked error, am I missing something in the configuration, I have configured nodes with default configurations, that are mentioned in the repo. 
If I increase the rate from 1000 per second then it's crashing also.  

`Insert Users  Create Users Err &{0xc0000f2d00 INSERT INTO ip_usernames (endpoint, username, domain_name, last_updated_timestamp) VALUES (?, ?, ?, ?) <nil> {{0 0} 0 0 0 0} 0xc0004b4080 <nil> <nil> {0 0} true [] 0} Error is database is locked (5) (SQLITE_BUSY)`
even after ingesting at a low rate, the database is getting locked.

**Comment by maxpert** [comment]
Marmot only acquires lock at boot time when trying to restore a snapshot, after that Marmot won't be locking DB (change lock tables might be locked but you are not directly dealing with them anyway). Are you booting up Marmot while doing some sort of snapshot restore?

**Comment by tania-anand** [comment]
No, I am not doing any such kind of thing.
**This is binary I am using of marmot 
marmot-v0.7.2-linux-amd64.tar.gz
for nat-server 
nats-server: v2.9.8
the server is ubuntu 14.04.6 
memory specs 4GB ram, and 4 cores.** 


Currently, I am inserting the values 1000 records per sec. 
and my target is to insert 5 million records, but after the insertion of 2 million records, marmot crashed. 
here is the stack trace file for that. 
[marmot.txt](https://github.com/maxpert/marmot/files/10175656/marmot.txt)

**Comment by maxpert** [comment]
Hey,

So looking at those logs, seems like your process is locking DB for pretty long times. Are you using transactions to insert into database? If yes, how often do you commit? Logs clearly show Marmot is trying to clean up change log tables and it keeps failing because DB from the insertion process is locked, or the changes published to NATS can't be applied to DB. Also I see snapshotting happening in the middle which is fine for low write scenario, but not really good for high write scenario like you described here. You should increase the `max_entries` in [your config.toml](https://github.com/maxpert/marmot/blob/master/config.toml#L66). 

Having said that I want to understand the use-case here as well. What is the DB for I see `ip_usernames`, `username_usergroup_mappings`, and `usergroups` from logs. Why are writes 1000 QPS? What are the row schemas looking like? Is it compress-able data (compression flag in configuration)? Because if it's not compress-able data then I will disable that too. One thing to remember is your network speed matter a lot in this case because if you are filling up DB faster than it can be published to NATS then there will always be some data lagging and sitting in your local buffers (Eventually it will converge, but will take time).

**Comment by maxpert** [comment]
Yes you need to bump that to even larger number something like `1000000` because this how quick rows are coming in, or disable snapshotting altogether if you don't really need snapshotting (by disabling [enabled](https://github.com/maxpert/marmot/blob/master/config.toml#L22)).

As for the question why it's crashing, I think process is receiving abort signal, as dump:
```
SIGABRT: abort
PC=0x7f09a0238c37 m=9 sigcode=18446744073709551610
signal arrived during cgo execution
```

For CGO calls I see two active callers doing a system call and stuck probably due to database being locked. Both these calls are trying necessary to function, one is to cleanup change log, and other one is to apply back change logs coming back from NATS. 

```
goroutine 44 [syscall]:
github.com/mattn/go-sqlite3._Cfunc__sqlite3_step_row_internal(0x7f0960037248, 0xc00034e458, 0xc00034e460)
	_cgo_gotypes.go:370 +0x4c
github.com/mattn/go-sqlite3.(*SQLiteStmt).execSync.func3(0xc0002ac2d0?, 0xc00009cd00?, 0x5?)
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3.go:2082 +0x65
github.com/mattn/go-sqlite3.(*SQLiteStmt).execSync(0xc0002ac2d0, {0xc00009cd00?, 0xc00034e100?, 0xc000297668?})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3.go:2082 +0x65
github.com/mattn/go-sqlite3.(*SQLiteStmt).exec(0xc0002ac2d0, {0xc861f8, 0xc0000b4090}, {0xc00009cd00?, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3.go:2044 +0x353
github.com/mattn/go-sqlite3.(*SQLiteStmt).ExecContext(0x0?, {0xc861f8, 0xc0000b4090}, {0xc00009cc30, 0x5, 0x418be7?})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3_go18.go:69 +0x8d
database/sql.ctxDriverStmtExec({0xc861f8, 0xc0000b4090}, {0xc86428, 0xc0002ac2d0}, {0xc00009cc30?, 0x5, 0x5})
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/ctxutil.go:65 +0xcc
database/sql.resultFromStatement({0xc861f8, 0xc0000b4090}, {0xc85980, 0xc001246420}, 0xc0003981c0, {0xc0000e4370, 0x5, 0x5})
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/sql.go:2663 +0x145
database/sql.(*Stmt).ExecContext(0xc0000cc120, {0xc861f8, 0xc0000b4090}, {0xc0000e4370, 0x5, 0x5})
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/sql.go:2636 +0x1fd
database/sql.(*Stmt).Exec(...)
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/sql.go:2651
github.com/maxpert/marmot/db.replicateUpsert(0x0?, 0xc0000e4190, 0xc?)
	/home/runner/work/marmot/marmot/db/change_log.go:498 +0x468
github.com/maxpert/marmot/db.replicateRow(0xc000297be0?, 0xc000297b60?, 0xc000297bd0?)
	/home/runner/work/marmot/marmot/db/change_log.go:468 +0x5b
github.com/maxpert/marmot/db.(*SqliteStreamDB).consumeReplicationEvent.func1(0x50?)
	/home/runner/work/marmot/marmot/db/change_log.go:161 +0x296
github.com/doug-martin/goqu/v9.(*Database).WithTx.func1()
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/database.go:108 +0x22
github.com/doug-martin/goqu/v9.(*TxDatabase).Wrap(0xc00007c820?, 0xc00019a000?)
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/database.go:647 +0x70
github.com/doug-martin/goqu/v9.(*Database).WithTx(0xc0000a6d98?, 0xc000297d20)
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/database.go:108 +0x69
github.com/maxpert/marmot/db.(*SqliteStreamDB).consumeReplicationEvent(0xc0000e4af0, 0xc0000e4190)
	/home/runner/work/marmot/marmot/db/change_log.go:145 +0xc9
github.com/maxpert/marmot/db.(*SqliteStreamDB).Replicate(...)
	/home/runner/work/marmot/marmot/db/change_log.go:69
main.onChangeEvent.func1({0xc0002fc1c0, 0xd4, 0x1aa})
	/home/runner/work/marmot/marmot/marmot.go:142 +0xcc
github.com/maxpert/marmot/logstream.(*Replicator).invokeListener(0xc0001b2270?, 0xc0002c6c00, 0xc0008b6cc0)
	/home/runner/work/marmot/marmot/logstream/replicator.go:244 +0x136
github.com/maxpert/marmot/logstream.(*Replicator).Listen(0xc000070940, 0xb8f3bb?, 0x0?)
	/home/runner/work/marmot/marmot/logstream/replicator.go:169 +0x36c
main.changeListener(0x0?, 0x0?, 0x0?, 0x0?)
	/home/runner/work/marmot/marmot/marmot.go:127 +0x85
created by main.main
	/home/runner/work/marmot/marmot/marmot.go:101 +0xb1f
```

```
goroutine 41 [syscall]:
github.com/mattn/go-sqlite3._Cfunc__sqlite3_step_row_internal(0x7f094800b0c8, 0xc0001a25b0, 0xc0001a25b8)
	_cgo_gotypes.go:370 +0x4c
github.com/mattn/go-sqlite3.(*SQLiteStmt).execSync.func3(0xc0003888d0?, 0xc00015c280?, 0x2?)
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3.go:2082 +0x65
github.com/mattn/go-sqlite3.(*SQLiteStmt).execSync(0xc0003888d0, {0xc00015c280?, 0xc00023da00?, 0x449005?})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3.go:2082 +0x65
github.com/mattn/go-sqlite3.(*SQLiteStmt).exec(0xc0003888d0, {0xc861f8, 0xc0000b4090}, {0xc00015c280?, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3.go:2044 +0x353
github.com/mattn/go-sqlite3.(*SQLiteConn).exec(0xc0002c6460?, {0xc861f8, 0xc0000b4090}, {0xc00002e230?, 0x2?}, {0xc00015c230, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3.go:875 +0x238
github.com/mattn/go-sqlite3.(*SQLiteConn).ExecContext(0xc881d8?, {0xc861f8, 0xc0000b4090}, {0xc00002e230, 0x49}, {0xc00015c190, 0x2, 0xc85030?})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.15/sqlite3_go18.go:41 +0xbb
database/sql.ctxDriverExec({0xc861f8?, 0xc0000b4090?}, {0x7f097666d0e0?, 0xc000f26720?}, {0x0?, 0x0?}, {0xc00002e230?, 0xc0002956c0?}, {0xc00015c190, 0x2, ...})
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/ctxutil.go:31 +0xe5
database/sql.(*DB).execDC.func2()
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/sql.go:1681 +0x175
database/sql.withLock({0xc83ac8, 0xc0000bc120}, 0xc000295870)
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/sql.go:3437 +0x8c
database/sql.(*DB).execDC(0x49?, {0xc861f8, 0xc0000b4090}, 0xc0000bc120, 0xc000295a00?, {0xc00002e230, 0x49}, {0xc0000c6560, 0x2, 0x2})
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/sql.go:1676 +0x266
database/sql.(*Tx).ExecContext(0xc0001a4280, {0xc861f8, 0xc0000b4090}, {0xc00002e230, 0x49}, {0xc0000c6560, 0x2, 0x2})
	/opt/hostedtoolcache/go/1.18.7/x64/src/database/sql/sql.go:2491 +0xb7
github.com/doug-martin/goqu/v9.(*TxDatabase).ExecContext(0xc00015c050, {0xc861f8, 0xc0000b4090}, {0xc00002e230, 0x49}, {0xc0000c6560, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/database.go:521 +0x93
github.com/doug-martin/goqu/v9/exec.QueryExecutor.ExecContext({{0xc83d48, 0xc00015c050}, {0x0, 0x0}, {0xc00002e230, 0x49}, {0xc0000c6560, 0x2, 0x2}}, {0xc861f8, ...})
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/exec/query_executor.go:45 +0xa9
github.com/doug-martin/goqu/v9/exec.QueryExecutor.Exec(...)
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/exec/query_executor.go:38
github.com/maxpert/marmot/db.(*SqliteStreamDB).cleanupChangeLog.func1(0x50?)
	/home/runner/work/marmot/marmot/db/change_log.go:334 +0x3ab
github.com/doug-martin/goqu/v9.(*Database).WithTx.func1()
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/database.go:108 +0x22
github.com/doug-martin/goqu/v9.(*TxDatabase).Wrap(0xc00007cd20?, 0x1?)
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/database.go:647 +0x70
github.com/doug-martin/goqu/v9.(*Database).WithTx(0xc0000a6d98?, 0xc000295da8)
	/home/runner/go/pkg/mod/github.com/doug-martin/goqu/v9@v9.18.0/database.go:108 +0x69
github.com/maxpert/marmot/db.(*SqliteStreamDB).cleanupChangeLog(0xc0000e4af0, {0xc00034e800?, 0xc?, {0xc00034e800?, 0x1?}})
	/home/runner/work/marmot/marmot/db/change_log.go:328 +0x14d
github.com/maxpert/marmot/db.(*SqliteStreamDB).publishChangeLog(0xc0000e4af0)
	/home/runner/work/marmot/marmot/db/change_log.go:314 +0x306
github.com/maxpert/marmot/db.(*SqliteStreamDB).watchChanges(0x0?, 0xc00007cff0, {0xc0000ec840, 0x20})
	/home/runner/work/marmot/marmot/db/change_log.go:227 +0x232
created by github.com/maxpert/marmot/db.(*SqliteStreamDB).InstallCDC
	/home/runner/work/marmot/marmot/db/sqlite.go:180 +0x2a5
```

From initial inspection this log seems to indicate some sort of external signal asking to abort while system calls are in progress. If I have to guess for crash I believe it will be the locked DB and since the default timeout is 5 seconds (I have change-set sitting locally to address that), the timeout might be causing the CGO to panic out and cause the issue. As you insert more and more rows just remember the insertion time does go up if you are not constantly optimizing DB. 

Is your intention to use this process as primary only publisher? Is NATS running on the same machine where Marmot, and your process is running? I am asking because I have bunch of changes I am experimenting with to have publish only and replicate only capability. If that is the case, may be you can help me test those changes.

**Comment by tania-anand** [comment]
okay, I will try to increase the max entries.
 yes, the use case is to publish the result to all clusters from primary and yes NATS is running on the same machine.
 sure,  can help you into test those changes.

**Comment by maxpert** [comment]
> yes, the use case is to publish the result to all clusters from primary and yes NATS is running on the same machine.

I guessed it by looking at number of times NATS didn't respond in time. You are essentially thrashing your system, and the machine is struggling to keep up with writes coming through (Your writes + 2 Marmot writes + NATS write + Periodic snapshots). Given the resources you described above I believe you are not having correct results on benchmark.

**Comment by maxpert** [comment]
OK so I generated a beta build https://github.com/maxpert/marmot/releases/tag/v0.7.3-beta.1 for you to test it out. Please not changes have not been fully tested by me, but this will essentially let you control write-only/read-only behavior.

**Comment by maxpert** [comment]
@tania-anand were you able to test the changes?

**Comment by tania-anand** [comment]
yeah, I was able to test the changes, seems like it was working, ran into another issue related to NATS-connection, will confirm once that issue is resolved.

**Comment by tania-anand** [comment]
Hi, @maxpert I have tested with the given changes, for 5 million rows, being inserted at a rate of 512 rows in 5 secs. I didn't face any issues, the system didn't crash. Hence closing the issue.
