### ISSUE TITLE
Raft groups should not share one state machine

### ISSUE THREAD

**Issue by losfair** [maxpert/marmot#7]
It looks like [a shared state machine is used](https://github.com/maxpert/marmot/blob/15feaadfd56262afd360af7baff9e33ad0fc416f/lib/raft.go#L294) for multiple Raft groups. This doesn't seem correct to me?

My understanding is that the Multi-Raft protocol does not guarantee commit order across different Raft groups. The user has to implement a custom distributed transaction layer (e.g. 2PC, or with some addition like Percolator or TrueTime) to establish partial ordering between transactions. TiKV uses Percolator, for example.

**Comment by maxpert** [comment]
So Marmot distributes rows across raft groups by Hashing table name and primary keys. This ensures a specific row always lands on same group. That will ensure row level change ordering. Marmot does not aim to solve table level change ordering to keep itself light weight. The other important thing to note is transactions will eventually boil down to physical writes, and these writes is what Marmot aims to replicate across cluster rather than order of transactions. So you are right about the fact that transactions won't be ordered, because that is not a goal for v1.

**Comment by losfair** [comment]
Does this mean mutations in the same transaction won't be atomic, and _re-ordering_ can happen?

For example:

```sql
BEGIN;
INSERT INTO table1 (k, v) VALUES('a', '1');
INSERT INTO table1 (k, v) VALUES('b', '2');
COMMIT;
```

can be observed in all 4 states (no items, 'a' only, 'b' only, 'a' and 'b').

**Comment by maxpert** [comment]
Yes, I've already called out this being eventually consistent, and `SERIALIZABLE` is usually not applicable. Let me explicitly callout `SERIALIZABLE` won't hold anymore.

**Comment by maxpert** [comment]
Added explicit callout to limitations [here](https://github.com/maxpert/marmot#limitations)

**Comment by maxpert** [comment]
Also on second thought I think I will move to having separate state machines for each cluster, that will let me do optimizations across the system, but I will still hold the limitations of eventual consistency in place. One interesting thing that I can do in order to sequence commit changes record the order of changes emitted by triggers in a global table as well (Right now there is per table change log). Then I can use that table as a reference into other tables. This might need a little deeper exploration. I will keep this thread posted as I do experimentation with it.

**Comment by maxpert** [comment]
I've got the first version out with independent state-machines. It has caused another issue in `SQLiteLogDB` though, so I've reverted back to default log DB backed by Pebble DB (takes more space on disk). I will follow up with fix for that and tracking it [here](https://sibte.notion.site/Explore-if-row-order-can-be-serialized-across-the-cluster-using-something-basic-3e8c333cca414e3a90e6e2e6b76c1dd1).

**Comment by maxpert** [comment]
Since we moved away to NATS this is not an issue anymore.
